const KEYBOARD_KEYS = [
	[
		{ key: 'W', keyCode: 'KeyW' },
		{ key: 'Q', keyCode: 'KeyQ' },
		{ key: 'E', keyCode: 'KeyE' },
		{ key: 'R', keyCode: 'KeyR' },
		{ key: 'T', keyCode: 'KeyT' },
		{ key: 'Y', keyCode: 'KeyY' },
		{ key: 'U', keyCode: 'KeyU' },
		{ key: 'I', keyCode: 'KeyI' },
		{ key: 'O', keyCode: 'KeyO' },
		{ key: 'P', keyCode: 'KeyP' },
		{ key: '´', keyCode: 'BracketLeft' },
	],
	[
		{ key: 'A', keyCode: 'KeyA' },
		{ key: 'S', keyCode: 'KeyS' },
		{ key: 'D', keyCode: 'KeyD' },
		{ key: 'F', keyCode: 'KeyF' },
		{ key: 'G', keyCode: 'KeyG' },
		{ key: 'H', keyCode: 'KeyH' },
		{ key: 'J', keyCode: 'KeyJ' },
		{ key: 'K', keyCode: 'KeyK' },
		{ key: 'L', keyCode: 'KeyL' },
		{ key: 'Ñ', keyCode: 'Semicolon' },
	],
	[
		{ key: 'Z', keyCode: 'KeyZ' },
		{ key: 'X', keyCode: 'KeyX' },
		{ key: 'C', keyCode: 'KeyC' },
		{ key: 'V', keyCode: 'KeyV' },
		{ key: 'B', keyCode: 'KeyB' },
		{ key: 'N', keyCode: 'KeyN' },
		{ key: 'M', keyCode: 'KeyM' },
		{ key: ',', keyCode: 'Comma' },
		{ key: '.', keyCode: 'Period' },
		{ key: 'Del', keyCode: 'Backspace' },
	],
	[{ key: 'Spc', keyCode: 'Space' }],
];

const ALLOWED_KEYS = [
	'KeyA',
	'KeyB',
	'KeyC',
	'KeyD',
	'KeyE',
	'KeyF',
	'KeyG',
	'KeyH',
	'KeyI',
	'KeyJ',
	'KeyK',
	'KeyL',
	'KeyM',
	'KeyN',
	'KeyÑ',
	'KeyO',
	'KeyP',
	'KeyQ',
	'KeyR',
	'KeyS',
	'KeyT',
	'KeyU',
	'KeyV',
	'KeyW',
	'KeyX',
	'KeyY',
	'KeyZ',
	'Enter',
	'Backspace',
	'Semicolon',
	'Space',
	'Period',
	'Comma',
	'BracketLeft',
];

const VOWELS = ['A', 'E', 'I', 'O', 'U', 'a', 'e', 'i', 'o', 'u'];

export { KEYBOARD_KEYS, ALLOWED_KEYS, VOWELS };
